name: haune-browser

services:
  manager:
    image: haune-browser:latest
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ~/.haune-browser:/data
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN:-}
